/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CollectionRouteImport } from './routes/collection'
import { Route as FavouritesRouteImport } from './routes/favourites'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TrophiesRouteImport } from './routes/trophies'
import { Route as CollectionIndexRouteImport } from './routes/collection.index'
import { Route as CollectionMakeRouteImport } from './routes/collection.$make'
import { Route as HistoryIndexRouteImport } from './routes/history.index'
import { Route as HistoryIdRouteImport } from './routes/history.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionRoute = CollectionRouteImport.update({
  id: '/collection',
  path: '/collection',
  getParentRoute: () => rootRouteImport,
} as any)
const FavouritesRoute = FavouritesRouteImport.update({
  id: '/favourites',
  path: '/favourites',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TrophiesRoute = TrophiesRouteImport.update({
  id: '/trophies',
  path: '/trophies',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionIndexRoute = CollectionIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CollectionRoute,
} as any)
const CollectionMakeRoute = CollectionMakeRouteImport.update({
  id: '/$make',
  path: '/$make',
  getParentRoute: () => CollectionRoute,
} as any)
const HistoryIndexRoute = HistoryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HistoryRoute,
} as any)
const HistoryIdRoute = HistoryIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => HistoryRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/collection': typeof CollectionRouteWithChildren
  '/favourites': typeof FavouritesRoute
  '/history': typeof HistoryRouteWithChildren
  '/scan': typeof ScanRoute
  '/settings': typeof SettingsRoute
  '/trophies': typeof TrophiesRoute
  '/collection/$make': typeof CollectionMakeRoute
  '/history/$id': typeof HistoryIdRoute
  '/collection/': typeof CollectionIndexRoute
  '/history/': typeof HistoryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/favourites': typeof FavouritesRoute
  '/scan': typeof ScanRoute
  '/settings': typeof SettingsRoute
  '/trophies': typeof TrophiesRoute
  '/collection/$make': typeof CollectionMakeRoute
  '/history/$id': typeof HistoryIdRoute
  '/collection': typeof CollectionIndexRoute
  '/history': typeof HistoryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/collection': typeof CollectionRouteWithChildren
  '/favourites': typeof FavouritesRoute
  '/history': typeof HistoryRouteWithChildren
  '/scan': typeof ScanRoute
  '/settings': typeof SettingsRoute
  '/trophies': typeof TrophiesRoute
  '/collection/$make': typeof CollectionMakeRoute
  '/history/$id': typeof HistoryIdRoute
  '/collection/': typeof CollectionIndexRoute
  '/history/': typeof HistoryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/collection'
    | '/favourites'
    | '/history'
    | '/scan'
    | '/settings'
    | '/trophies'
    | '/collection/$make'
    | '/history/$id'
    | '/collection/'
    | '/history/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/favourites'
    | '/scan'
    | '/settings'
    | '/trophies'
    | '/collection/$make'
    | '/history/$id'
    | '/collection'
    | '/history'
  id:
    | '__root__'
    | '/'
    | '/collection'
    | '/favourites'
    | '/history'
    | '/scan'
    | '/settings'
    | '/trophies'
    | '/collection/$make'
    | '/history/$id'
    | '/collection/'
    | '/history/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CollectionRoute: typeof CollectionRouteWithChildren
  FavouritesRoute: typeof FavouritesRoute
  HistoryRoute: typeof HistoryRouteWithChildren
  ScanRoute: typeof ScanRoute
  SettingsRoute: typeof SettingsRoute
  TrophiesRoute: typeof TrophiesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collection': {
      id: '/collection'
      path: '/collection'
      fullPath: '/collection'
      preLoaderRoute: typeof CollectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favourites': {
      id: '/favourites'
      path: '/favourites'
      fullPath: '/favourites'
      preLoaderRoute: typeof FavouritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trophies': {
      id: '/trophies'
      path: '/trophies'
      fullPath: '/trophies'
      preLoaderRoute: typeof TrophiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collection/': {
      id: '/collection/'
      path: '/'
      fullPath: '/collection/'
      preLoaderRoute: typeof CollectionIndexRouteImport
      parentRoute: typeof CollectionRoute
    }
    '/collection/$make': {
      id: '/collection/$make'
      path: '/$make'
      fullPath: '/collection/$make'
      preLoaderRoute: typeof CollectionMakeRouteImport
      parentRoute: typeof CollectionRoute
    }
    '/history/': {
      id: '/history/'
      path: '/'
      fullPath: '/history/'
      preLoaderRoute: typeof HistoryIndexRouteImport
      parentRoute: typeof HistoryRoute
    }
    '/history/$id': {
      id: '/history/$id'
      path: '/$id'
      fullPath: '/history/$id'
      preLoaderRoute: typeof HistoryIdRouteImport
      parentRoute: typeof HistoryRoute
    }
  }
}

interface CollectionRouteChildren {
  CollectionMakeRoute: typeof CollectionMakeRoute
  CollectionIndexRoute: typeof CollectionIndexRoute
}

const CollectionRouteChildren: CollectionRouteChildren = {
  CollectionMakeRoute: CollectionMakeRoute,
  CollectionIndexRoute: CollectionIndexRoute,
}

const CollectionRouteWithChildren = CollectionRoute._addFileChildren(
  CollectionRouteChildren,
)

interface HistoryRouteChildren {
  HistoryIdRoute: typeof HistoryIdRoute
  HistoryIndexRoute: typeof HistoryIndexRoute
}

const HistoryRouteChildren: HistoryRouteChildren = {
  HistoryIdRoute: HistoryIdRoute,
  HistoryIndexRoute: HistoryIndexRoute,
}

const HistoryRouteWithChildren =
  HistoryRoute._addFileChildren(HistoryRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CollectionRoute: CollectionRouteWithChildren,
  FavouritesRoute: FavouritesRoute,
  HistoryRoute: HistoryRouteWithChildren,
  ScanRoute: ScanRoute,
  SettingsRoute: SettingsRoute,
  TrophiesRoute: TrophiesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
